artist:
  name: Jonas Williams
  # tagline: Jonas is a reggae singer living in Groningen, the Netherlands
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  contact_phone: 0031623432432
  contact_email: jroos7@gmail.com

social:
  - name: Youtube
    url: https://youtube.com/channel/UCBHincbiDJxDoHjTdpMQ5Sg
  

site_language: en
